name: Keep Render Backend Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:       # Allows manual triggering

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render backend
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://classtrack-backend-ovl2.onrender.com/ping
